WEEKDAYS = (
    (0, 'Monday'),
    (1, 'Tuesday'),
    (2, 'Wednesday'),
    (3, 'Thursday'),
    (4, 'Friday'),
    (5, 'Saturday'),
    (6, 'Sunday'),
)

STATUS_CHOICES = [
    ('NS', 'Not Sent'),
    ('AW', 'Awaiting Acceptance'),
    ('A', 'Accepted'),
    ('R', 'Ready'),
    ('T', 'Retired'),
]
TAG_CHOICES = [
    ('pizza', 'Pizza'),
    ('pasta', 'Pasta'),
    ('chinese_cuisine', 'Chinese Cuisine'),
    ('japanese_cuisine', 'Japanese Cuisine'),
    ('mexican_cuisine', 'Mexican Cuisine'),
    ('indian_cuisine', 'Indian Cuisine'),
    ('thai_cuisine', 'Thai Cuisine'),
    ('french_cuisine', 'French Cuisine'),
    ('italian_cuisine', 'Italian Cuisine'),
    ('spanish_cuisine', 'Spanish Cuisine'),
    ('greek_cuisine', 'Greek Cuisine'),
    ('american_cuisine', 'American Cuisine'),
    ('mediterranean_cuisine', 'Mediterranean Cuisine'),
    ('vegetarian_cuisine', 'Vegetarian Cuisine'),
    ('vegan_cuisine', 'Vegan Cuisine'),
    ('seafood', 'Seafood'),
    ('steakhouse', 'Steakhouse'),
    ('bbq', 'BBQ'),
    ('sushi', 'Sushi'),
    ('burger', 'Burger'),
    ('salad', 'Salad'),
    ('dessert', 'Dessert'),
    ('breakfast', 'Breakfast'),
    ('brunch', 'Brunch'),
    ('dinner', 'Dinner'),
    ('fast_food', 'Fast Food'),
    ('casual_dining', 'Casual Dining'),
    ('fine_dining', 'Fine Dining'),
    ('cafe', 'Cafe'),
    ('buffet', 'Buffet'),
    ('street_food', 'Street Food'),
    ('fusion', 'Fusion'),
    ('organic', 'Organic'),
    ('gluten_free', 'Gluten Free'),
    ('halal', 'Halal'),
    ('kosher', 'Kosher'),
    ('lebanese_cuisine', 'Lebanese Cuisine'),
    ('turkish_cuisine', 'Turkish Cuisine'),
    ('vietnamese_cuisine', 'Vietnamese Cuisine'),
    ('korean_cuisine', 'Korean Cuisine'),
    ('brazilian_cuisine', 'Brazilian Cuisine'),
    ('argentinian_cuisine', 'Argentinian Cuisine'),
    ('ethiopian_cuisine', 'Ethiopian Cuisine'),
    ('caribbean_cuisine', 'Caribbean Cuisine'),
    ('peruvian_cuisine', 'Peruvian Cuisine'),
    ('cuban_cuisine', 'Cuban Cuisine'),
    ('russian_cuisine', 'Russian Cuisine'),
    ('german_cuisine', 'German Cuisine'),
    ('polish_cuisine', 'Polish Cuisine'),
    ('moroccan_cuisine', 'Moroccan Cuisine'),
    ('egyptian_cuisine', 'Egyptian Cuisine'),
    ('portuguese_cuisine', 'Portuguese Cuisine'),
    ('african_cuisine', 'African Cuisine'),
    ('south_african_cuisine', 'South African Cuisine'),
    ('australian_cuisine', 'Australian Cuisine'),
    ('british_cuisine', 'British Cuisine'),
    ('belgian_cuisine', 'Belgian Cuisine'),
    ('dutch_cuisine', 'Dutch Cuisine'),
    ('swedish_cuisine', 'Swedish Cuisine'),
    ('norwegian_cuisine', 'Norwegian Cuisine'),
    ('danish_cuisine', 'Danish Cuisine'),
    ('finnish_cuisine', 'Finnish Cuisine'),
    ('swiss_cuisine', 'Swiss Cuisine'),
    ('austrian_cuisine', 'Austrian Cuisine'),
    ('hungarian_cuisine', 'Hungarian Cuisine'),
    ('romanian_cuisine', 'Romanian Cuisine'),
    ('czech_cuisine', 'Czech Cuisine'),
    ('slovak_cuisine', 'Slovak Cuisine'),
    ('slovenian_cuisine', 'Slovenian Cuisine'),
    ('croatian_cuisine', 'Croatian Cuisine'),
    ('serbian_cuisine', 'Serbian Cuisine'),
    ('bosnian_cuisine', 'Bosnian Cuisine'),
    ('montenegrin_cuisine', 'Montenegrin Cuisine'),
    ('macedonian_cuisine', 'Macedonian Cuisine'),
    ('bulgarian_cuisine', 'Bulgarian Cuisine'),
    ('albanian_cuisine', 'Albanian Cuisine'),
    ('georgian_cuisine', 'Georgian Cuisine'),
    ('armenian_cuisine', 'Armenian Cuisine'),
    ('azerbaijani_cuisine', 'Azerbaijani Cuisine'),
    ('kazakh_cuisine', 'Kazakh Cuisine'),
    ('uzbek_cuisine', 'Uzbek Cuisine'),
    ('turkmen_cuisine', 'Turkmen Cuisine'),
    ('tajik_cuisine', 'Tajik Cuisine'),
    ('kyrgyz_cuisine', 'Kyrgyz Cuisine'),
    ('mongolian_cuisine', 'Mongolian Cuisine'),
    ('nepalese_cuisine', 'Nepalese Cuisine'),
    ('sri_lankan_cuisine', 'Sri Lankan Cuisine'),
    ('bangladeshi_cuisine', 'Bangladeshi Cuisine'),
    ('pakistani_cuisine', 'Pakistani Cuisine'),
    ('afghan_cuisine', 'Afghan Cuisine'),
    ('persian_cuisine', 'Persian Cuisine'),
    ('iraqi_cuisine', 'Iraqi Cuisine'),
    ('syrian_cuisine', 'Syrian Cuisine'),
    ('jordanian_cuisine', 'Jordanian Cuisine'),
    ('palestinian_cuisine', 'Palestinian Cuisine'),
    ('israeli_cuisine', 'Israeli Cuisine'),
    ('saudi_cuisine', 'Saudi Cuisine'),
]
