# Generated by Django 5.0.6 on 2024-05-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_address_alter_restaurant_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('street', 'city', 'state', 'country')},
        ),
    ]
