# Generated by Django 5.0.6 on 2024-05-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_dish_ingredient_menu_menusection_dish_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
    ]
