# Generated by Django 5.0.6 on 2024-05-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_menu_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
