# Generated by Django 5.0.6 on 2024-05-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_rename_name_dish_dname_rename_name_menusection_sname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusection',
            name='sname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
