# Generated by Django 5.0.6 on 2024-05-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_menusection_sname'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('section', 'dname')},
        ),
    ]
