# Generated by Django 5.0.6 on 2024-05-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_openinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusection',
            name='sname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='menusection',
            unique_together={('menu', 'sname')},
        ),
    ]
