# Generated by Django 5.0.6 on 2024-06-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_order_status_activeorderitem_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Sent'), ('AW', 'Awaiting Acceptance'), ('A', 'Accepted'), ('R', 'Ready'), ('T', 'Retired')], default='NA', max_length=2),
        ),
    ]
