# Generated by Django 5.0.6 on 2024-06-09 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_address_unique_together'),
        ('restaurants', '0019_restaurant_banner_restaurant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='accounts.address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
