# Generated by Django 5.0.6 on 2024-06-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_alter_restaurant_address_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_seats',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
