# Generated by Django 5.0.6 on 2024-06-09 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('street', 'city', 'state', 'country')},
        ),
    ]
